import {Frase} from '../shared/frase.model'

export const FRASES: Array<Frase>=[
    {fraseEng : "I like to learn",  frasePTBR :"Eu gosto de estudar"},
    {fraseEng : "I watch TV",       frasePTBR :"Eu vejo TV"},
    {fraseEng : "How are you?",     frasePTBR :"Como você vai"},
    {fraseEng : "I eat bread",      frasePTBR :"Eu como pão"},
    {fraseEng : "What is your name?",  frasePTBR :"Qual é o seu nome?"},
    {fraseEng : "My name is Jake.",  frasePTBR :"Meu nome é Jake."},
    {fraseEng : "Hello. How are you?",  frasePTBR :"Oi. Como está você? Como vai você? Tudo bem?"},
    {fraseEng : "I am fine, and you?",  frasePTBR :"Eu estou bem, e você?"},
    {fraseEng : "Nice to meet you!",  frasePTBR :"Prazer em te conhecer!"},
    {fraseEng : "Nice to meet you too.",  frasePTBR :"O prazer é meu."},
    {fraseEng : "What time is it?",  frasePTBR :"Que horas são?"},
    {fraseEng : "I am hungry!",  frasePTBR :"Estou com fome!"},
    {fraseEng : "I am thirsty!",  frasePTBR :"Estou com sede!"},
    {fraseEng : "I am hot.",  frasePTBR :"Eu estou com calor."},
    {fraseEng : "I am cold.",  frasePTBR :"Estou com frio."},
    {fraseEng : "How old are you?",  frasePTBR :"Qual é a sua idade?"},
    {fraseEng : "Where are you from?",  frasePTBR :"De onde você é?"},
    {fraseEng : "I'm from Brazil.",  frasePTBR :"Eu sou do Brasil."},
    {fraseEng : "Please.",  frasePTBR :"Por favor."},
    {fraseEng : "Excuse me.",  frasePTBR :"Com licença."},
    {fraseEng : "I'm sorry.",  frasePTBR :"Desculpa. Me desculpa. Lamento."},
    {fraseEng : "Have a nice weekend.",  frasePTBR :"Tenha um bom final de semana."},
    {fraseEng : "You too.",  frasePTBR :"Você também. Para você também."},
    {fraseEng : "Where do you live?",  frasePTBR :"Onde você mora?"},
    {fraseEng : "How much?",  frasePTBR :"Quanto custa? Quanto é? Qual é o valor?"},
    {fraseEng : "Are you married or single?",  frasePTBR :"Você é casado ou solteiro? Você é casada ou solteira?"},
    {fraseEng : "What do you do? I am a lawyer.",  frasePTBR :"Qual é a sua profissão? Eu sou advogado."},
    {fraseEng : "Do you have any children?",  frasePTBR :"Você tem filhos?"},
    {fraseEng : "Do you have any brothers or sisters?",  frasePTBR :"Você tem irmãos?"},
    {fraseEng : "I'm late.",  frasePTBR :"Estou atrasado."},
    {fraseEng : "I miss you.",  frasePTBR :"Estou com saudades de você."},
    {fraseEng : "I'm sorry I'm late.",  frasePTBR :"Desculpe o atraso."},
    {fraseEng : "Can I help you?",  frasePTBR :"Posso ajudar?"},
    {fraseEng : "Can you help me?",  frasePTBR :"Você pode me ajudar?"},
    {fraseEng : "How is the weather?",  frasePTBR :"Como está o tempo? Como está o clima?"},
    {fraseEng : "I love you.",  frasePTBR :"Eu te amo."},
    {fraseEng : "I need.",  frasePTBR :"Eu preciso."},
    {fraseEng : "I want.",  frasePTBR :"Eu quero."},
    {fraseEng : "I know.",  frasePTBR :"Eu sei. Eu conheço."},
    {fraseEng : "I don't know.",  frasePTBR :"Eu não sei. Eu não conheço."},
    {fraseEng : "I knew.",  frasePTBR :"Eu sabia. Eu conhecia."},
    {fraseEng : "I didn't know.",  frasePTBR :"Eu não sabia. Eu não conhecia."},
    {fraseEng : "Would you like some juice?",  frasePTBR :"Você aceita suco? Quer suco?"},
    {fraseEng : "Where is the restroom / bathroom?",  frasePTBR :"Onde é o banheiro?"},
    {fraseEng : "I like it. I like you. I like ice cream.",  frasePTBR :"Eu gosto disto. Eu gosto de você. Eu gosto de sorvete."},
    {fraseEng : "Stop. Don't go. Stay here.",  frasePTBR :"Pare. Não vá. Fique aqui."},
    {fraseEng : "What do you think about Brazil?",  frasePTBR :"O que você acha do Brasil?"},
    {fraseEng : "I think Brazil is a great country.",  frasePTBR :"Eu acho o Brasil um ótimo país."},
    {fraseEng : "Be careful. It's dangerous.",  frasePTBR :"Tenha cuidado. É perigoso."},
    {fraseEng : "Are you OK?",  frasePTBR :"Está tudo bem com você?"},
    {fraseEng : "I'm now well.",  frasePTBR :"Eu não estou bem."},
    {fraseEng : "Good luck.",  frasePTBR :"Boa sorte."},
    {fraseEng : "Have a nice trip.",  frasePTBR :"Boa viagem."},
    {fraseEng : "When is your birthday?",  frasePTBR :"Quando é o seu aniversário?"},
    {fraseEng : "Is there a hotel near here?",  frasePTBR :"Tem um hotel aqui perto?"},
    {fraseEng : "Enjoy your meal!",  frasePTBR :"Bom apetite!"},
    {fraseEng : "Get well soon!",  frasePTBR :"Melhoras! Fique bem logo!"},
    {fraseEng : "Have fun!",  frasePTBR :"Divirta-se!"},
    {fraseEng : "Please wait a moment.",  frasePTBR :"Por favor, espere um momento."},
    {fraseEng : "Let's go. It's time.",  frasePTBR :"Vamos. Está na hora."},
    {fraseEng : "Don't speak loudly.",  frasePTBR :"Não fale alto."},
    {fraseEng : "Could you please speak more slowly?",  frasePTBR :"Você poderia por favor falar mais devagar?"}
]



